apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-cost-guard
  namespace: kubernetes-cost-guard
  labels:
    app.kubernetes.io/name: kubernetes-cost-guard
    app.kubernetes.io/part-of: kubernetes-cost-guard
